---
- name: PROMETHEUS | Check for prometheus user
  getent:
    database: passwd
    key: "{{ prometheus_user }}"
    fail_key: False

- name: PROMETHEUS | Check for prometheus group
  getent:
    database: passwd
    key: "{{ prometheus_group }}"
    fail_key: False

- name: PROMETHEUS | Ensure Prometheus group
  group:
    name: "{{ prometheus_group }}"
    system: yes
    state: present
  when: getent_passwd[prometheus_group] == none

- name: PROMETHEUS | Ensure Prometheus user
  user:
    name: "{{ prometheus_user }}"
    comment: "prometheus user account"
    createhome: no
    system: yes
    shell: /bin/false
  when: getent_passwd[prometheus_user] == none

- include_tasks: install-prometheus.yml
  static: no